### ISSUE TITLE
Could you provide more information on how to fix Linux microphone? Thanks!

### ISSUE THREAD

**Issue by nmnmcc** [Data-Name-ID/RedmiBook-Pro-14-2024#4]

**Comment by Data-Name-ID** [comment]
The microphone doesn't work on Linux yet. Wait for updates.

**Comment by intzaaa** [comment]
> The microphone doesn't work on Linux yet. Wait for updates.

Where can I check the progress?

**Comment by nmnmcc** [comment]
> The microphone doesn't work on Linux yet. Wait for updates.

Where can I check the progress?

**Comment by Data-Name-ID** [comment]
I'm not the one doing Linux compatibility, stay tuned for article updates manually. I can write here when it appears

**Comment by nmnmcc** [comment]
Thanks!
________________________________
发件人: Data Name ID ***@***.***>
发送时间: 2024年7月25日 下午 02:27
收件人: Data-Name-ID/RedmiBook-Pro-14-2024 ***@***.***>
抄送: Intza ***@***.***>; Author ***@***.***>
主题: Re: [Data-Name-ID/RedmiBook-Pro-14-2024] Could you provide more information on how to fix Linux microphone? Thanks! (Issue #4)


I'm not the one doing Linux compatibility, stay tuned for article updates manually. I can write here when it appears

―

**Comment by god1dog** [comment]
https://github.com/OrelSokolov/redmibook-dummy-output-fix?tab=readme-ov-file

**Comment by god1dog** [comment]
@Data-Name-ID why is there no update readme
